#!/usr/bin/env bash

# trope AIO installer

SRCDIR="${HOME}/trope-1shot"
SRC="./main.py"
DEST="/usr/local/bin/trope"
DESTP="/usr/local/bin/pacman"

die () {
    if [ $? -gt 0 ]; then
        echo "$*" 1>&2 ; exit 1;
    fi
}

echo "Welcome to trope installer"

asksym () {
    read -r optsym
    case $optsym in
        'y') :;;
        'n') :;;
        *)
            printf "Please answer y or n: "
            asksym
            ;;
    esac
}

printf "Symlink /usr/local/bin/trope to /usr/local/bin/pacman? (make the \'pacman\' command work) [y/n]: "
asksym

echo "Cloning repository to ${SRCDIR} ..." ; git clone https://github.com/joznia/trope.git ${SRCDIR} > /dev/null 2>&1
cd ${SRCDIR}
echo "Copying trope to /usr/local/bin ..." ; sudo cp $SRC $DEST 
echo "Setting permissions ..." ; sudo chmod 0755 $DEST
case $optsym in
    'y')
        echo "Symlinking trope to pacman ..."
        sudo ln -sf $DEST $DESTP
        sudo chmod 0755 $DESTP
        ;;
    'n')
        :;;
esac

echo "Removing repository..." ; rm -rf ${SRCDIR}

